options:
  logrotate-retention:
    type: int
    default: 180
    description: |
      The logrotate retention period in days. The charm will go through `ALL`
      logrotate entries in /etc/logrotate.d/ and set the `rotate` config to
      the appropriate value, depending on the rotation interval used.
      For example if rotation is monthy and retention is 180 days -> `rotate 6`
      or rotation is daily and retention is 90 days -> `rotate 90`
      or rotation is weekly and retention is 21 days -> `rotate 3`
      Weekly will round up the week count, for example if retention is set
      to 180 days -> `rotate 26` (26 weeks x 7 days = 182 days)
      Yearly will put rotate to 1 and increase it with 1 for each 360 days.
  logrotate-cronjob:
    type: boolean
    default: True
    description: |
      Enabled or disables the creation of a cronjob for the automatic updating
      of the logrotate files.
  logrotate-cronjob-frequency:
    type: string
    default: 'hourly'
    description: |
      If logrotate-cronjob is True, then this value is used to determine the
      location of the cronjob file.
      Valid options are 'hourly', 'daily', 'weekly', 'monthly'.
