#!/usr/bin/env python3
"""Install-hook entry point."""

import os
import sys


def configure_charm_tmp(
    environ=os.environ,
    hook_path=__file__,
):
    """Use a private temporary directory on the charm filesystem."""
    charm_dir = environ.get("JUJU_CHARM_DIR")
    if not charm_dir:
        hook_dir = os.path.dirname(os.path.abspath(hook_path))
        charm_dir = os.path.dirname(hook_dir)

    tmp_dir = os.path.join(charm_dir, "tmp")
    os.makedirs(tmp_dir, mode=0o700, exist_ok=True)
    os.chmod(tmp_dir, 0o700)
    environ["TMPDIR"] = tmp_dir
    return tmp_dir


def main():
    """Bootstrap and run the reactive charm."""
    configure_charm_tmp()
    sys.path.append("lib")

    from charms.layer import basic

    basic.bootstrap_charm_deps()

    from charmhelpers.core import hookenv

    hookenv.atstart(basic.init_config_states)
    hookenv.atexit(basic.clear_config_states)

    from charms.reactive import main as reactive_main

    reactive_main()


if __name__ == "__main__":
    main()
