#!/usr/bin/env python3

import os
import sys

os.environ['TMPDIR'] = '/var/tmp'

sys.path.append('lib')

from charms.layer import basic  # noqa
basic.bootstrap_charm_deps()

from charmhelpers.core import hookenv  # noqa
hookenv.atstart(basic.init_config_states)
hookenv.atexit(basic.clear_config_states)

from charms.reactive import main  # noqa
main()
